from enum import IntEnum

CELLMAP_WIDTH = 150
CELLMAP_HEIGHT = 150

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 1200

CELL_WIDTH = SCREEN_WIDTH / CELLMAP_WIDTH
CELL_HEIGHT = SCREEN_HEIGHT / CELLMAP_HEIGHT

FILL_CELL = 0

SHOW_FPS = True
SHOW_LATENCY = True
SHOW_GENERATION = True

FPS = None
PAUSED = True

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)

DEAD = 0
ALIVE = 1
DYING = 2